# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: å¼ å“å¦‚,web,å‰ç«¯,hexo,Butterfly,vue
# å¯è®¾ç½®ä¸»é¡µä¸­æ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜æˆ–è€…å–œæ¬¢çš„åº§å³é“­
subtitle:
  enable: true
  # Typewriter Effect (æ‰“å­—æ•ˆæœ)
  effect: true
  # loop (å¾ªç’°æ‰“å­—)
  loop: true
  # sourceèª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨æå¤©apiçš„éš¨æ©ŸèªéŒ„ï¼ˆç°¡é«”ï¼‰
  # source: 2  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰
  # source: 3  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰
  # source: 4  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: false
  # å¦‚æœæœ‰è‹±æ–‡é€—è™Ÿ' , ',è«‹ä½¿ç”¨è½‰ç¾©å­—å…ƒ &#44;
  # å¦‚æœæœ‰è‹±æ–‡é›™å¼•è™Ÿ' " ',è«‹ä½¿ç”¨è½‰ç¾©å­—å…ƒ &quot;
  # é–‹é ­ä¸å…è¨±è½‰ç¾©å­—å…ƒï¼Œå¦‚éœ€è¦ï¼Œè«‹æŠŠæ•´å€‹å¥å­ç”¨é›™å¼•è™ŸåŒ…ä½
  # å¦‚æœé—œé–‰æ‰“å­—æ•ˆæœï¼Œsubtitleåªæœƒé¡¯ç¤ºsubçš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub: 
    # - å¤šçœ‹ä¹¦ï¼Œå¤šçœ‹æŠ¥ï¼›å°‘ç©ç”µè„‘ï¼Œå¤šç¡è§‰ã€‚
    - é‡å˜å¼•èµ·è´¨å˜ï¼ŒçŸ¥è¯†åœ¨äºç§¯ç´¯ğŸ˜˜ã€‚
    - å¥½è®°æ€§ä¸å¦‚çƒ‚ç¬”å¤´ğŸ¤£ã€‚
description: ''
keywords: å¼ å“å¦‚,web,å‰ç«¯,hexo,Butterfly,vue
author: ZhuoRu
language: zh-CN
timezone: 'Asia/Shanghai'
# å¤´åƒ
avatar:
  img: https://bu.dusays.com/2022/05/02/626f92e193879.jpg
# ç¤¾äº¤åœ–æ¨™
social:
  fab fa-github: https://github.com/WebZhuoRu || Github
  fas fa-envelope: mailto:2276839311@qq.com || Email
  fa-solid fa-book-skull: https://webzhuoru.github.io/ || åšå®¢

# ä¸»é æ–‡ç« ç¯€é¸
index_post_content:
  method: 2
  length: 500 # if you set method to 2 or 3, the length need to config
# Website Background (è¨­ç½®ç¶²ç«™èƒŒæ™¯)
# can set it to color or image (å¯è¨­ç½®åœ–ç‰‡ æˆ–è€… é¡”è‰²)
# The formal of image: url(http://xxxxxx.com/xxx.jpg)
background: '#efefef'
# é ‚éƒ¨åœ–
## ä¸»é çš„
index_img: "./img/test.jpg"
##é»˜èª
default_top_img: "./img/test.jpg"
##æ­¸æª”
archive_img: "./img/bg.jpg"

cover:
  # æ˜¯å¦é¡¯ç¤ºæ–‡ç« å°é¢
  index_enable: true
  aside_enable: true
  archives_enable: true
  # å°é¢é¡¯ç¤ºçš„ä½ç½®
  # ä¸‰å€‹å€¼å¯é…ç½® left , right , both
  position: both
  # ç•¶æ²’æœ‰è¨­ç½®coveræ™‚ï¼Œé»˜èªçš„å°é¢é¡¯ç¤º
  default_cover: 
    - /img/tab1.png
    - /img/tab2.png
    - /img/tab3.png
    - /img/tab4.png
    - /img/tab5.png
    - /img/tab6.png
    - /img/tab99.png
# æ–‡ç« ç‰ˆæ¬Š
post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
# ç›¸é—œæ–‡ç« 
related_post:
  enable: true
  limit: 6 # é¡¯ç¤ºæ¨è–¦æ–‡ç« æ•¸ç›®
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸé¡¯ç¤ºå‰µå»ºæ—¥æˆ–è€…æ›´æ–°æ—¥

# æ–‡ç« æ‰“è³
reward:
  enable: true
  QR_code:
    - img: /img/wechat.png
      link:
      text: å¾®ä¿¡
    - img: /img/alipay.jpg
      link:
      text: æ”¯ä»˜å¯¶
# åœ–ç‰‡æè¿°
photofigcaption: true
# copy settings
# copyright: Add the copyright information after copied content (è¤‡è£½çš„å…§å®¹å¾Œé¢åŠ ä¸Šç‰ˆæ¬Šä¿¡æ¯)
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50
# åšå®¢å¹´ä»½
footer:
  owner:
    enable: true
    since: 2019
  # é¡µè„šè‡ªå®šä¹‰æ–‡æœ¬
  custom_text: I wish you to become your own sun, no need to rely on who's light.<p><a target="_blank" href="https://hexo.io/"><img src="https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo" title="åšå®¢æ¡†æ¶ä¸ºHexo"></a>&nbsp;<a target="_blank" href="https://butterfly.js.org/"><img src="https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender" title="ä¸»é¢˜é‡‡ç”¨butterfly"></a>&nbsp;<a target="_blank" href="https://www.jsdelivr.com/"><img src="https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr" title="æœ¬ç«™ä½¿ç”¨JsDelivrä¸ºé™æ€èµ„æºæä¾›CDNåŠ é€Ÿ"></a> &nbsp;<a target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Vervel-brightgreen?style=flat&logo=Vercel" title="æœ¬ç«™é‡‡ç”¨åŒçº¿éƒ¨ç½²ï¼Œé»˜è®¤çº¿è·¯æ‰˜ç®¡äºVercel"></a>&nbsp;<a target="_blank" href="https://vercel.com/ "><img src="https://img.shields.io/badge/Hosted-Coding-0cedbe?style=flat&logo=Codio" title="æœ¬ç«™é‡‡ç”¨åŒçº¿éƒ¨ç½²ï¼Œè”é€šçº¿è·¯æ‰˜ç®¡äºCoding"></a>&nbsp;<a target="_blank" href="https://github.com/"><img src="https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub" title="æœ¬ç«™é¡¹ç›®ç”±Gtihubæ‰˜ç®¡"></a>&nbsp;<a target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris" title="æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯"></a></p>
  copyright: false
# A simple 404 page
error_404:
  enable: true
  subtitle: "é¡µé¢æ²’æœ‰æ‰¾åˆ°"
  background: 
# è®¿é—®äººæ•°(UV å’Œ PV)
busuanzi:
  site_uv: true  # æœ¬ç«™æ€»è®¿å®¢æ•°
  site_pv: true  # æœ¬ç«™æ€»è®¿é—®é‡ 
  page_pv: true  # æœ¬æ–‡æ€»é˜…è¯»é‡
# ç½‘é¡µå·²è¿è¡Œæ—¶é—´
runtimeshow:
  enable: true
  publish_date: 7/1/2019 00:00:00  
  ##ç½‘é¡µå¼€é€šæ—¶é—´
  #æ ¼å¼: æœˆ/æ—¥/å¹´ æ—¶é—´
  #ä¹Ÿå¯ä»¥å†™æˆ å¹´/æœˆ/æ—¥ æ—¶é—´
# footeræ˜¯å¦æ˜¾ç¤ºå›¾ç‰‡èƒŒæ™¯(ä¸top_imgä¸€è‡´)
footer_bg: true
# ç®€ç¹è½¬æ¢
translate:
  enable: false
  # é»˜è®¤æŒ‰é’®æ˜¾ç¤ºæ–‡å­—(ç½‘ç«™æ˜¯ç®€ä½“ï¼Œåº”è®¾ç½®ä¸º'default: ç¹')
  default: ç¹
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chineseï¼‰
  # ç½‘ç«™é»˜è®¤è¯­è¨€ï¼Œ1: ç¹ä½“ä¸­æ–‡, 2: ç®€ä½“ä¸­æ–‡
  defaultEncoding: 2
  # Time delay å»¶è¿Ÿæ—¶é—´,è‹¥ä¸åœ¨å‰, è¦è®¾å®šå»¶è¿Ÿç¿»è¯‘æ—¶é—´, å¦‚100è¡¨ç¤º100ms,é»˜è®¤ä¸º0
  translateDelay: 0
  # å½“æ–‡å­—æ˜¯ç®€ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToTraditionalChinese: 'ç¹'
  # å½“æ–‡å­—æ˜¯ç¹ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToSimplifiedChinese: 'ç°¡'
# å¤œé—´æ¨¡å¼

darkmode:
  enable: true
  # dark å’Œ light ä¸¤ç§æ¨¡å¼åˆ‡æ¢æŒ‰é’®
  button: true
  # Switch dark/light mode automatically (è‡ªå‹•åˆ‡æ› dark modeå’Œ light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  autoChangeMode: false
  # autoChangeMode: 1
aside:
  enable: true
  hide: false
  button: true
  mobile: true # æ‰‹æ©Ÿé é¢ï¼ˆ é¡¯ç¤ºå¯¬åº¦ < 768px ï¼‰æ˜¯å¦é¡¯ç¤ºasideå…§å®¹
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/WebZhuoRu
  card_announcement:
    enable: true
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
# Typewriter Effect (æ‰“å­—æ•ˆæœ)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: true
  colorful: true # open particle animation (å†’å…‰ç‰¹æ•ˆ)
  shake: true #  open shake (æŠ–å‹•ç‰¹æ•ˆ)
  mobile: false
# Mouse click effects: fireworks (é¼ æ¨™é»æ“Šæ•ˆæœ: ç…™ç«ç‰¹æ•ˆ)
fireworks:
  enable: false
  zIndex: 9999 # -1 or 9999
# ç‚¹å‡»å‡ºç¾çˆ±å¿ƒ
click_heart:
  enable: true
  mobile: false
# å…¨å±€å­—ä½“
font:
  global-font-size:
  code-font-size:
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  code-font-family: consolas, Menlo, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  # Font settings for the site title and site subtitle
  # å·¦ä¸Šè§’ç½‘ç«™åå­— ä¸»é¡µå±…ä¸­ç½‘ç«™åå­—
  blog_title_font:
    font_link: https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
    font-family: Titillium Web, 'PingFang SC', 'Hiragino Sans GB', 'Microsoft JhengHei', 'Microsoft YaHei', sans-serif

# åŠ è½½åŠ¨ç”» Loading Animation
preloader: true
# preloader:
#     enable: true # true|false
#     load_color: '#000000' # '#37474f'
#     load_style: wizard # default|gear|ironheart|scarecrow|triangles|wizard|image


# Default display mode (ç¶²ç«™é»˜èªçš„é¡¯ç¤ºæ¨¡å¼)
# light (default) / dark
display_mode: dark
# Lazyload (åœ–ç‰‡æ‡¶åŠ è¼‰)
# https://github.com/verlok/lazyload
lazyload:
  enable: true
  post: /img/loading.gif
# Snackbar (Toast Notification å½ˆçª—)  // æ“ä½œæç¤ºå¼¹çª—
# https://github.com/polonel/SnackBar
# position å½ˆçª—ä½ç½®
# å¯é¸ top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
snackbar:
  enable: true
  position: top-right
  bg_light: '#49b1f5' # The background color of Toast Notification in light mode
  bg_dark: '#121212' # The background color of Toast Notification in dark mode
# Lightbox (åœ–ç‰‡å¤§åœ–æŸ¥çœ‹æ¨¡å¼)
# fancybox http://fancyapps.com/fancybox/3/
fancybox: true

# Open graph meta tags
# https://developers.facebook.com/docs/sharing/webmasters/
Open_Graph_meta: true
# Caches the contents in a fragment, speed up the generation (é–‹å•Ÿ hexo è‡ªå¸¶çš„ç·©å­˜, åŠ å¿«ç”Ÿæˆé€Ÿåº¦)
fragment_cache: true
# Inject the css and script (aplayer/meting)
aplayerInject:
  enable: true
  per_page: true
# å¦‚æœä½ æœ‰ä½¿ç”¨hexo-doubanï¼Œå¯é…ç½®è¿™ä¸ª
pjax: 
  enable: true
# Local search
local_search:
  enable: true
# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# æ’å…¥ä»£ç åˆ°å¤´éƒ¨ </head> ä¹‹å‰ å’Œ åº•éƒ¨ </body> ä¹‹å‰            // å¤–æŒ‚æ–¹å¼å¼•å…¥è‡ªå®šä¹‰ CSS å’Œ JS, æ¨èåœ¨è¿™é‡Œå¼•å…¥è‡ªå®šä¹‰ CSS å’Œ JS
inject:
  head:
    ## æ˜Ÿç©ºèƒŒæ™¯
    # - <link rel="stylesheet" href="/css/loading_wizard.css"/>
    # - <link rel="stylesheet" href="/css/frosted_glass.css"/>
    - <link rel="stylesheet" href="/css/custom.css">
    - <link rel="stylesheet" href="https://fastly.jsdelivr.net/gh/tzy13755126023/BLOG_SOURCE/css/function.min.css">
    - <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" media="defer" onload="this.media='all'">
    # - <link rel="stylesheet" href="/xxx.css">
    # - <link rel="stylesheet" href="/css/frosted_glass.css"/>
  bottom:
    # - <script src="xxxx"></script>
    # æ˜Ÿç©ºèƒŒæ™¯
    - <canvas id="universe"></canvas>
    - <div class="aplayer no-destroy" data-id="7592292364" data-server="netease" data-type="playlist" data-fixed="true" data-autoplay="true" data-loop="all" data-lrctype="0"> </div>
    - <script defer src="https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js"></script>
    - <script defer src="/js/universe.js"></script>
    - <script defer src="/js/sun_moon.js"></script>
    - <script defer src="https://fastly.jsdelivr.net/gh/graingert/wow@1.3.0/dist/wow.min.js"></script>
    - <script defer data-pjax src="/js/wow_init.js"></script>
# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://webzhuoru.github.io/
# permalink: :year/:month/:day/:title/
permalink: post/:abbrlink.html # postä¸ºè‡ªå®šä¹‰å‰ç¼€
abbrlink:
  alg: crc32   #ç®—æ³•ï¼š crc16(default) and crc32
  rep: hex     #è¿›åˆ¶ï¼š dec(default) and hex
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# åˆ†ç±»å’Œæ ‡ç­¾
# é»˜è®¤åˆ†ç±»
default_category: uncategorized
#åˆ†ç±»åˆ«å
category_map: Butterfly CSS Github JavaScript Node React Vue uni-app æ¨èåˆ†äº« éšç¬”
#æ ‡ç­¾åˆ«å
tag_map: Butterfly CSS Github JavaScript Node React Vue uni-app æ¨èåˆ†äº« éšç¬”

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# menu
menu:
  é¦–é¡µ: / || fas fa-home
  æ—¶é—´è½´: /archives/ || fas fa-archive
  æ ‡ç­¾: /tags/ || fas fa-tags
  åˆ†ç±»: /categories/ || fas fa-folder-open
  èµåŠ©å¢™: /sponsorWall/ || fas fa-images
  # æ¸…å•||fa fa-heartbeat:
  #   éŸ³ä¹: /music/ || fas fa-music
  #   ç…§ç‰‡: /Gallery/ || fas fa-images
  #   ç”µå½±: /movies/ || fas fa-video
  å‹é“¾: /link/ || fas fa-link
  å…³äº: /about/ || fas fa-heart

#ä»£ç é«˜äº®ä¸»é¢˜
highlight_theme: mac
highlight_copy: true
highlight_shrink: false #ä»£ç æ¡†å±•å¼€ï¼Œæœ‰>ç‚¹å‡»æŒ‰é’®
highlight_height_limit: 500 # å•ä½æ˜¯pxï¼Œç›´æ¥æ·»åŠ æ•°å­—ï¼Œå¦‚ 200
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:webzhuoru/webzhuoru.github.io.git
  branch: main

# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: all # åº”ç”¨é¡µé¢
  timemode: date #date/updated
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: id
    name: recent-posts
    index: 0
  default_descr: å†æ€ä¹ˆçœ‹æˆ‘ä¹Ÿä¸çŸ¥é“æ€ä¹ˆæè¿°å®ƒçš„å•¦ï¼
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper cssä¾èµ–
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper jsä¾èµ–
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # é€‚é…ä¸»é¢˜æ ·å¼è¡¥ä¸
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiperåˆå§‹åŒ–æ–¹æ³•

  # hexo-filter-gitcalendar
# see https://akilar.top/posts/1f9c68c9/
gitcalendar:
  enable: true # å¼€å…³
  priority: 5 #è¿‡æ»¤å™¨ä¼˜å…ˆæƒ
  enable_page: / # åº”ç”¨é¡µé¢
  # butterflyæŒ‚è½½å®¹å™¨
  layout: # æŒ‚è½½å®¹å™¨ç±»å‹
    type: id
    name: recent-posts
    index: 0
  # volantisæŒ‚è½½å®¹å™¨
  # layout:
  #   type: class
  #   name: l_main
  #   index: 0
  # materyæŒ‚è½½å®¹å™¨
  # layout:
  #   type: id
  #   name: indexCard
  #   index: 0
  # mengdæŒ‚è½½å®¹å™¨
  # layout:
  #   type: class
  #   name: content
  #   index: 0
  user: webzhuoru #gitç”¨æˆ·å
  apiurl: 'https://api-webzhuoru.vercel.app'
  minheight:
    pc: 280px #æ¡Œé¢ç«¯æœ€å°é«˜åº¦
    mibile: 0px #ç§»åŠ¨ç«¯æœ€å°é«˜åº¦
  # color: "['#e4dfd7', '#f9f4dc', '#f7e8aa', '#f7e8aa', '#f8df72', '#fcd217', '#fcc515', '#f28e16', '#fb8b05', '#d85916', '#f43e06']" #æ©˜é»„è‰²è°ƒ
  # color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']" #æµ…ç´«è‰²è°ƒ
  # color: "['#ebedf0', '#f0fff4', '#dcffe4', '#bef5cb', '#85e89d', '#34d058', '#28a745', '#22863a', '#176f2c', '#165c26', '#144620']" #ç¿ ç»¿è‰²è°ƒ
  color: "['#ebedf0', '#f1f8ff', '#dbedff', '#c8e1ff', '#79b8ff', '#2188ff', '#0366d6', '#005cc5', '#044289', '#032f62', '#05264c']" #å¤©é’è‰²è°ƒ
  container: .recent-post-item(style='width:100%;height:auto;padding:10px;') #çˆ¶å…ƒç´ å®¹å™¨ï¼Œéœ€è¦ä½¿ç”¨pugè¯­æ³•
  gitcalendar_css: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.css
  gitcalendar_js: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.js

# å‹é“¾æ ·å¼ï¼Œbutterflyä¸ºé»˜è®¤æ ·å¼ï¼Œvolantisä¸ºç«™ç‚¹å¡ç‰‡æ ·å¼.flexcardä¸ºå¼¹æ€§å¡ç‰‡æ ·å¼
flink_style: flexcard # butterfly | volantis | flexcard